### ISSUE TITLE
Debug Sticks do not work across servers

### ISSUE THREAD

**Issue by Madscience763** [MultiPaper/MultiPaper#208]
![image](https://user-images.githubusercontent.com/104371439/177890797-d621f38c-2827-49a7-85e8-1957b0a538c0.png)

**Comment by PureGero** [comment]
Debug sticks appear to work for me. Can you send a video if they still don't work?

**Comment by Madscience763** [comment]
https://user-images.githubusercontent.com/104371439/180893359-24219e62-e3cf-4d75-a486-05ad9318777c.mp4

**Comment by PureGero** [comment]
It appears to work fine for me
- Which `/version` is this?
- How do you place the debug stick into your inventory - perhaps that is not being synced with the other server.
- Try relogging with a debug stick in your inventory and see if it starts working

**Comment by Madscience763** [comment]
Before I was using 1.19-13. It still happens on 1.19-15
I got it through the creative inventory saved hotbar. I tried dropping it and picking it up again, giving it, and getting it from a chest and same issue still happens. 
Relogging does not fix it

**Comment by Madscience763** [comment]
As far a I can tell this is an issue with permissions, tested with /op and it works fine
