### ISSUE TITLE
You Are already connected to this server [ERROR]

### ISSUE THREAD

**Issue by S0ly** [MultiPaper/MultiPaper#236]
i can't switch from one Node to Another even whit a plugin 
 the bungee connect me and then kick me 
 
 im on the last version of everything in 1.19.2 java
![image](https://user-images.githubusercontent.com/86328249/183750527-29e62fbb-d24a-4639-adbc-da30888fa67e.png)

**Comment by PureGero** [comment]
It's a design flaw with bungeecord and velocity where it will connect you to the destination server before disconnecting you from the current server. If you try to connect a player to one MultiPaper server while they're still on another MultiPaper server, it will say they're already online and refuse the connection.

**Comment by S0ly** [comment]
Can you maybe make a command ?

**Comment by S0ly** [comment]
Please
