### ISSUE TITLE
sleeping plugin issue

### ISSUE THREAD

**Issue by S0ly** [MultiPaper/MultiPaper#238]
so sleeping plugin seems to have issue whit multipaper

to reproduce :
having a sleeping plugin
2 node
1 master
1 bungeecord
whit all the node started etc and the plugin only on one node

what is happening :
sleeping plugin seems to not recieve the event wen the player enter a bed and so sometimes does not count the player as sleeping or does not send message

to fix this error :
retart the other node and the plugin will now revieve the event and start sending message

it seems that its a sync problem or i don't know

**Comment by S0ly** [comment]
ho and i want to add that sleeping player position are wierd :
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/86328249/184049656-14e9bcd6-f069-418d-a0c3-886f9fc2899f.png">

**Comment by PureGero** [comment]
This means the plugin is not compatible with MultiPaper.
