### ISSUE TITLE
Why player send message show Not Secure

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#241]
Plugins:
`Plugins (14): BungeeGuard, Chunky, DiscordSRV, InvSee, LoneLibs, LuckPerms, Orebfuscator, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SlimeChunk, TabTPS, WorldEdit, Wraith`
Version:
`This server is running MultiPaper version git-MultiPaper-"61dc438" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 61dc438)
You are running the latest version`

When player send message, console will show
`[Not Secure] <YT_iceice> test`
And didn't show any error

**Comment by Madscience763** [comment]
That is if the player has no chat signature. Completely normal

**Comment by KaspianDev** [comment]
> Plugins: `Plugins (14): BungeeGuard, Chunky, DiscordSRV, InvSee, LoneLibs, LuckPerms, Orebfuscator, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SlimeChunk, TabTPS, WorldEdit, Wraith` Version: `This server is running MultiPaper version git-MultiPaper-"61dc438" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 61dc438) You are running the latest version`
> 
> When player send message, console will show `[Not Secure] <YT_iceice> test` And didn't show any error

its just not signed, not insecure, idk why they use such scary naming

**Comment by ham1255** [comment]
Well, mojang naming

**Comment by YTiceice** [comment]
Ok, thanks your help
