### ISSUE TITLE
Unloading and deleting world directory causes server crash

### ISSUE THREAD

**Issue by alex6777** [MultiPaper/MultiPaper#243]
I have the following code that unloads the world after it's used:

```
File f = new File(world.getName() + "/");
boolean unloaded = Bukkit.unloadWorld(world, false);
Bukkit.broadcastMessage("unloaded: " + unloaded); // Prints true

if (f.isDirectory()) {
   try {
      FileUtils.deleteDirectory(f);
   } catch (IOException e) {
      e.printStackTrace();         
   }
}
```

but it spams this until it crashes:
https://pastebin.com/raw/ueUQ6aMd

Is unloading worlds supported?

**Comment by ham1255** [comment]
Have you checked if Bukkit unloadWorld method finished instead of being blocked?

**Comment by ham1255** [comment]
i found out that it happens because in the code, it uses 

`Bukkit#getWorld(UUID uid)` or string equivalent is marked as nullable in bukkit api
which means it can return null, which then calling`CraftWorld#getHandle()` throws the `NullPointerExepction`
created pr for that

**Comment by tomaica1934** [comment]
is there fix for this yet?

**Comment by tomaica1934** [comment]
bump pls fix

**Comment by ham1255** [comment]
can you stop posting useless posts please?

**Comment by tomaica1934** [comment]
fix pls
请修复它我无法卸载世界

**Comment by PureGero** [comment]
Why are worlds being unloaded?

**Comment by ham1255** [comment]
Any world that created in bukkit api can be unloaded, i just got those errors *they are rare* which in pull request i created solves that issue, and also about server hanging not sure about that
