### ISSUE TITLE
Phantom Blocks and Inventory Items incorrect

### ISSUE THREAD

**Issue by DIDIRUS4** [MultiPaper/MultiPaper#246]
Sometimes players put blocks under themselves and they disappear - the player eventually falls one block down. It looks like it's a phantom block. In addition, sometimes there are bugs with phantom incorrect things in the inventory, for example, after death or when a player gets a lot of things at once. Latest version, 1.19.2

**Comment by PureGero** [comment]
Please upload videos showing these things happening.

**Comment by DIDIRUS4** [comment]
> Please upload videos showing these things happening.

I don't have any videos, I'll close this problem, maybe it was because of the Internet + TCP Shield, I need testers, so I'm looking for them to implement my ideas. Therefore, as soon as I gather testers, I will probably publish errors here if there are any
