### ISSUE TITLE
SUGGESTION: Implement Petal patches into MultiPaper

### ISSUE THREAD

**Issue by AnghiYt** [MultiPaper/MultiPaper#253]
Hi. 

Since within MultiPaper, there are optimizations from Airplane and Pufferfish, it would be interesting to have Petal optimizations (similar to those of pufferfish+). This would lead to a performance increase of 10 to 20% (declared by some users on discord servers) approaching the 25-30% declared by the pufferfish+ developer.

Link: https://github.com/Bloom-host/Petal

"Petal is a performance-oriented fork of Purpur intended to increase performance for entity-heavy servers by implementing multi-threaded and asynchronous improvements."

"Petal focuses on two specific improvements for entity-heavy servers:

- **Async Pathfinding**: Entity pathfinding is offloaded to asynchronous threads to significantly reduce processing from the main thread
- **Multi-threaded Entity Tracking**: Entity tracking can take advantage of multiple threads to greatly reduce dependence on main thread processing"

Although these patches work, some users have encountered some problems, such as mobs that do not move in the water, but only rotate (https://github.com/Bloom-host/Petal/issues/12), or, the occasional disappearance of npc player type (https://github.com/Bloom-host/Petal/issues/3). 

For these small issues the petal devs have stated that they are rewriting the patches to optimize them and fix these things.

So, in case you don't want to add these patches and then update them when they are rewritten, I will write on this post when they are updated so that you can implement them directly.

**NOTE**: From what I understand these patches have also been included in pufferfish, so, I do not know if they should be taken from Petal or Pufferfish, this part I leave to you.

**Comment by Madscience763** [comment]
They were supposed to be added a while ago but right now dupes take priority.

**Comment by AnghiYt** [comment]
> They were supposed to be added a while ago but right now dupes take priority.

Yes, I think so too. I just wanted to leave for this writing, so it doesn't get lost over time

**Comment by ham1255** [comment]
it seems like petal was abandoned, should i close this?

**Comment by kugge** [comment]
> it seems like petal was abandoned, should i close this?

If they want to use petal patches they should set petal as upstream. Those instable patches are way too time-consuming to maintain. Same with experimental patches from forks such as gale, suki...

**Comment by ham1255** [comment]
> > it seems like petal was abandoned, should i close this?
> 
> 
> 
> If they want to use petal patches they should set petal as upstream. It should be easy since pufferfish patches have been removed. Petal instable patches are way too time-consuming to maintain. Same with experimental patches from forks such as gale, suki...

Yes but it wouldn't work on 1.19.2 or 1.19.3 i think due chunk system rewrite in paper. Anyways i am closing this.
