### ISSUE TITLE
Facing a block bug

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#254]
When I facing a block, I can't eat or perform other right-click actions, details in the video
[YouTube](https://youtu.be/90JCyKZHPxI)

plugins:
`Plugins (17): AntiPopup, BungeeGuard, ChatPreview, DiscordSRV, InvSee, LoneLibs, LuckPerms, Orebfuscator, PlaceholderAPI, PlayerLogger*, PlugManX (PlugMan), ProtocolLib, SlimeChunk*, TabTPS, TaiwanifyEveryItem, WorldEdit, Wraith`
version:
`This server is running MultiPaper version git-MultiPaper-"6ce43aa" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6ce43aa)`

**Comment by PureGero** [comment]
Does it occur without any plugins?

**Comment by YTiceice** [comment]
No, I am sorry

**Comment by YTiceice** [comment]
oh, is caused by Wraith
