### ISSUE TITLE
spawn protection didn't work

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#260]
![image](https://user-images.githubusercontent.com/87787929/190659740-0b1ac91d-64a0-411b-99a7-47bf99b428f6.png)
I set `spawn-protection` to `16`, then restart MultiPaper and MultiPaperMaster, but it didn't work, no op's player still can break block

**Comment by PureGero** [comment]
Was the bug fixed? Or was it not actually a bug?

**Comment by YTiceice** [comment]
Sorry, I didn't remove the op permission for testing
