### ISSUE TITLE
Command /locate crash server

### ISSUE THREAD

**Issue by Jeleyk** [MultiPaper/MultiPaper#285]
Command "locate" for some structures causes the server to crash.
For example: /locate structure buried_treasure

**Comment by ham1255** [comment]
I wouldn't say its crash, because server is still calculating things internally, but server watchdog kicks in and kills it

**Comment by Madscience763** [comment]
Same issue as the treasure map bug. The command searches for the closest location of the structure. often into ungenerated chunks, not a multipaper issue

**Comment by PureGero** [comment]
See https://bugs.mojang.com/browse/MC-250276
