### ISSUE TITLE
SUGGESTION: Be able to mode players between servers

### ISSUE THREAD

**Issue by BasToTheMax** [MultiPaper/MultiPaper#287]
There should be a `mpmove <username> <server_id>` command on the master to move players. ;D

**Comment by PureGero** [comment]
The master is not in charge of which server the players are on. This is the job of your proxy, eg BungeeCord, Velocity, HAProxy, etc

**Comment by BasToTheMax** [comment]
I don't use a proxy. I use the standalone master to proxy

**Comment by BasToTheMax** [comment]
I just switched to bungeecord, but the servers don't show up
![image](https://user-images.githubusercontent.com/55401336/197841549-d79c6c35-8299-413b-bc1b-173503ffc45b.png)

**Comment by BasToTheMax** [comment]
> There should be a `mpmove <username> <server_id>` command on the master to move players. ;D

I mean that the master would be able to move players between multipaper servers
