### ISSUE TITLE
WARNING MALWARE 

### ISSUE THREAD

**Issue by Miriam0** [MultiPaper/MultiPaper#296]
![image](https://user-images.githubusercontent.com/46651542/204921878-3a19684a-5eea-427b-a8c7-b8532f20a857.png)
i found this when i start multipaper downloaded from official server

**Comment by Miriam0** [comment]
https://www.virustotal.com/gui/file/9713217dce153a8dc326d069dbff3da1d9fb58678cafdeeb88e22a61db00b023

**Comment by catdogmat** [comment]
This may have been there before you ran mutipaper

**Comment by catdogmat** [comment]
Also Multipaper is open source so there is little chance it caused it

**Comment by PureGero** [comment]
Closing as unrelated to MultiPaper
