### ISSUE TITLE
in some cases i can't break blocks

### ISSUE THREAD

**Issue by Miriam0** [MultiPaper/MultiPaper#298]
i'v started mp with 2 slaves

in some chunks after /rtp i can't break blocks.
if i will /spawn and /back i will have ability to break blocks

**Comment by xymb-endcrystalme** [comment]
Sorry, I have no idea what `/rtp`, `/spawn` and `/back` are.
Does the problem persist when you run MultiPaper without plugins?

Because it sounds like it's caused by plugins.
