### ISSUE TITLE
Cannot use on big worlds

### ISSUE THREAD

**Issue by MarcoLvr** [MultiPaper/MultiPaper#302]
Hi,
I'm trying to use MultiPaper system on a very big world (120GB) but it seems to not work at all.
![image](https://user-images.githubusercontent.com/42388782/209486454-05458ba6-51ad-403d-9a17-4ab4630389f3.png)
in the photo you can see many of the thousand of warnings that the slave server sends per second and the machine stats (with the server off the machine uses 10GB and 30% of CPU). With a smaller world (256MB) it works perfectly so the problem isn't my machine.
Is there a fix?

**Comment by ham1255** [comment]
Where did you place the world file?

**Comment by MarcoLvr** [comment]
In the master folder
main folder:
![image](https://user-images.githubusercontent.com/42388782/209489479-a68d8b92-2c5e-407b-ad45-a8eb773eeea9.png)
master folder:
![image](https://user-images.githubusercontent.com/42388782/209489521-31933ef4-e1bf-4219-a219-0a3b36e735c8.png)
worker folder (plugins dir is empty):
![image](https://user-images.githubusercontent.com/42388782/209489551-c1988f8d-2d7f-4eae-9d8d-86ae8363e50c.png)

**Comment by ham1255** [comment]
You are using latest build of 1.19.2?

**Comment by MarcoLvr** [comment]
yes
[multipaper-1.19.2-37.jar](https://multipaper.io/api/v2/projects/multipaper/versions/1.19.2/builds/37/downloads/multipaper-1.19.2-37.jar)
[MultiPaper-Master-2.10.1-all.jar](https://multipaper.io/api/v2/projects/multipaper/versions/1.19.2/builds/37/downloads/MultiPaper-Master-2.10.1-all.jar)

**Comment by PedroMPagani** [comment]
> Hi,
> I'm trying to use MultiPaper system on a very big world (120GB) but it seems to not work at all.
> ![image](https://user-images.githubusercontent.com/42388782/209486454-05458ba6-51ad-403d-9a17-4ab4630389f3.png)
> in the photo you can see many of the thousand of warnings that the slave server sends per second and the machine stats (with the server off the machine uses 10GB and 30% of CPU). With a smaller world (256MB) it works perfectly so the problem isn't my machine.
> Is there a fix?

Are both worlds generated in the same version?

**Comment by MarcoLvr** [comment]
> > Hi,
> > I'm trying to use MultiPaper system on a very big world (120GB) but it seems to not work at all.
> > ![image](https://user-images.githubusercontent.com/42388782/209486454-05458ba6-51ad-403d-9a17-4ab4630389f3.png)
> > in the photo you can see many of the thousand of warnings that the slave server sends per second and the machine stats (with the server off the machine uses 10GB and 30% of CPU). With a smaller world (256MB) it works perfectly so the problem isn't my machine.
> > Is there a fix?
> 
> Are both worlds generated in the same version?

The world was generated in 1.18 and converted in 1.19.1 when the 1.19.1 was released. The world is pregenerated for the first 25k blocks from the center. I don't think that the version of the world is a problem because I used a smaller world but generated with 1.18 and the system worked perfectly

**Comment by MarcoLvr** [comment]
If it can help you the region folder contains ~120980158 files and the poi folder (of the same world) contains ~368554 files

**Comment by PedroMPagani** [comment]
What are the bandwidth specs on your node, have you checked if you're not going above the limit?

**Comment by MarcoLvr** [comment]
> What are the bandwidth specs on your node, have you checked if you're not going above the limit? (About the map) multipaper seem to have users that have a lot bigger maps than that, and they don't seem to be complaining this could be a problem because of the map being generated in a diff version, or might not be corelated at all.

The bandwidth is ok. I'll try to fix the world if possible and I'll tell you if works

**Comment by MarcoLvr** [comment]
I did several tests with other big worlds and the software worked flawlessly. Evidently the problem is actually the world
