### ISSUE TITLE
PersistentDataContainer not properly synced between servers

### ISSUE THREAD

**Issue by robertnisipeanu** [MultiPaper/MultiPaper#303]
The following two issues appears when using PersistentDataContainer with MultiPaper:

1. Secondary/slave servers having already loaded a chunk will not get a persistent data container update when the TileState.update() method is called. Secondary/slave servers that loads the chunk after the PDC and/or TileState update gets the data just fine.
2. When adding something to the PersistentDataContainer from a secondary/slave server, all the data is lost.
* secondary/slave server = Another server than the one owning the chunk.

The following plugin (source code can be found on: [https://github.com/robertnisipeanu/ContainerProtect](https://github.com/robertnisipeanu/ContainerProtect)) adds some information to each chest placed for protection purposes. That is, owner of the chest. 
The owner can also allow other players to access the chest using the `/cmodify` command and punching the chest.
To view information of a chest, any player can use the `/cinfo` command, followed by a punch on the chest. This will display the owner and all the players allowed to access the chest.

- Placing a chest and using the `/cinfo` command on the server owning the chunk, then switching the server to a slave which doesn't have the chunk loaded yet and running `/cinfo` again:
https://i.imgur.com/bZM2teY.mp4
**It's OK**

- Placing a chest on the server owning the chunk, then using `/cinfo` on a slave which already has the chunk loaded:
https://i.imgur.com/S7HWGvY.mp4
**It's not OK**. The PDC info was not shared.

- Placing a chest on the slave server, then using `/cinfo` on both the slave and the server owning the chunk:
https://i.imgur.com/9nIFoxV.mp4
**It's somewhat OK**. If you pay close attention to the chat, you can see that the server processing the block place event is actually the server owning the chunk, so the PDC is saved successfully, however that information is not shared back to the slave server (same behavior as previous point)

- Placing a chest on the server owning the chunk, using `/cmodify` to add access to another player, switching to the slave server (which doesn't have the chunk loaded), and using `/cinfo` to read the PDC. This example is just to show that the `/cmodify` command works as expected on one server
https://i.imgur.com/wf8YVZy.mp4
**It's OK**

- Placing a chest on the server owning the chunk, switch to the slave server (which doesn't have the chunk loaded), and using `/cmodify` to add another player to the chest
https://i.imgur.com/Ohjqj7n.mp4
**It's not OK**. After switching the server, using `/cinfo` returned the correct information (just like for the first bullet), however, once the `/cmodify` command was used, the PDC information was lost. Notice, that unlike the block place event (which I've mentioned in the third bullet), the PlayerInteractEvent for a left punch happens on the slave server, which results in the PDC being updated by the slave server, before it's lost forever in what I consider a bug.

Point of interests in the plugin code that handles the save:
Saving the PersistentDataContainer: https://github.com/robertnisipeanu/ContainerProtect/blob/master/src/main/java/com/nisipeanu/containerprotect/protection/Protection.java#L118
And updating the tilestate: https://github.com/robertnisipeanu/ContainerProtect/blob/master/src/main/java/com/nisipeanu/containerprotect/protection/TileProtection.java#L50-L52
BlockPlace event listener, which calls the above functions: https://github.com/robertnisipeanu/ContainerProtect/blob/master/src/main/java/com/nisipeanu/containerprotect/listeners/ProtectionAddListener.java
`/cinfo` command: https://github.com/robertnisipeanu/ContainerProtect/blob/master/src/main/java/com/nisipeanu/containerprotect/commands/ContainerInfo.java
`/cmodify` command: https://github.com/robertnisipeanu/ContainerProtect/blob/master/src/main/java/com/nisipeanu/containerprotect/commands/ContainerModify.java

**Comment by ham1255** [comment]
i would like to add something it seems like loading chunk from other server loads, and data exists there but problem is when you set the new data but it will not be synced either something isn't synced correctly
