### ISSUE TITLE
1.19.3 nether portal issue

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#305]
[video](https://youtu.be/j68ZKnrA-Aw)
Like video, when I enter nether portal and leave nether, server will create a new nether portal, then I back to origin nether portal, the nearby blocks are backtracked.

I have tried without any plugin, MultiPaper version:
`This server is running MultiPaper version git-MultiPaper-"00dee8c" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 00dee8c on dev/1.19.3)`

**Comment by ham1255** [comment]
This was reported in discord few weeks ago and i can confirm this happening too, still looking,,,

**Comment by YTiceice** [comment]
ok, thanks for your hard work

**Comment by ham1255** [comment]
End portals have not issue so far as i tested
but problem in this list below
```
Nether -> Overworld // nether resets where portal exists
Overworld -> Nether // overworld resets where portal exists
```
which makes me think, that chunks holder or tickets are vanishing out of thin air when player teleports
which then makes the server think no chunks exists and regenerate them

**Comment by ham1255** [comment]
Should be closed now!

**Comment by YTiceice** [comment]
Sorry, I was outside and didn't receive any notifications on my phone.
This issue has been fixed after testing with my players, thank you
