### ISSUE TITLE
Use Pufferfish as Upstream

### ISSUE THREAD

**Issue by kugge** [MultiPaper/MultiPaper#314]
Since paperweight allow us to use any paper fork as upstream it might be a good idea to think about portability (MultiPaper with any upstream, purpur, custom fork...).

Also, this will allow to avoid using deprecated functions, allowing automatic pufferfish patch updates...

If this is a "good idea" I can create a PR.

**Comment by PureGero** [comment]
Feel free to make a PR that sets pufferfish as the upstream instead of Paper

**Comment by ham1255** [comment]
You have to remove pufferfish patches too

**Comment by DoctaEnkoda** [comment]
I'm not for Pufferfish, they are not always up to date on PaperMc, why not rather at this stage, used Purpur if it is to really change the upstream ?

After Paper is clean enough, making fork of fork of fork..., is not a good idea I think.

**Comment by xymb-endcrystalme** [comment]
Purpur has some cool patches, I also think that it's a better choice than Pufferfish.

On the other hand if I was making MultiPaper I'd probably go the easiest road and just used Paper as Upstream cause less work...

**Comment by kugge** [comment]
I think we can apply MultiPaper to almost any Paper fork.
I removed every pufferfish patches, and applied this script:
https://gist.github.com/kugge/f106d76b559dc62d3f08605d531f249e
Although we must solve outdater paper dependencies such as `player.didPlayerJoinEvent` and `getActivePlayer(UUID)`

**Comment by ham1255** [comment]
> I think we can apply MultiPaper to almost any Paper fork. I removed every pufferfish/airplane patches, and applied this script: https://gist.github.com/kugge/f106d76b559dc62d3f08605d531f249e Although we must solve outdater paper dependencies such as `player.didPlayerJoinEvent` and `getActivePlayer(UUID)`

https://github.com/MultiPaper/MultiPaper/pull/313

**Comment by kugge** [comment]
> > I think we can apply MultiPaper to almost any Paper fork. I removed every pufferfish/airplane patches, and applied this script: https://gist.github.com/kugge/f106d76b559dc62d3f08605d531f249e Although we must solve outdater paper dependencies such as `player.didPlayerJoinEvent` and `getActivePlayer(UUID)`
> 
> https://github.com/MultiPaper/MultiPaper/pull/313

Thanks. I'll try to set pufferfish as upstream with your pr.
