### ISSUE TITLE
player when sees external entity might not see it animation, like on fire, skeleton uses the bow, player sneaking, flying with elytra etc [EntityMetaData]]

### ISSUE THREAD

**Issue by ham1255** [MultiPaper/MultiPaper#316]
Example creeper exploding:

https://cdn.discordapp.com/attachments/937309618743427116/1061699901383258212/2023-01-08_21-33-20.mp4

exists on branch 1.19.3 branch but not sure if on 1.19.2
at first i thought it was upstream patches that i merged, but it turns out to be something else.

**Comment by MadeByIToncek** [comment]
Does not exist in the latest version.

**Comment by ham1255** [comment]
> Does not exist in the latest version.

this on 1.19.3 dev branch not latest 1.19.2
