### ISSUE TITLE
Protocol Version not working

### ISSUE THREAD

**Issue by Tynopia** [MultiPaper/MultiPaper#324]
![image](https://user-images.githubusercontent.com/65678882/215345531-216f2efe-062d-45e4-9558-5464a53ab470.png)
![image](https://user-images.githubusercontent.com/65678882/215345538-c8d210ac-8397-47f0-a3cb-eccc47b95e2a.png)

`player.getProtocolVersion()`

I used this code to get the protcol version of the player. The problem is, that the version every time 760 is.
**I also tried it on other PCs and Versions but it still returns 760**

**Comment by ham1255** [comment]
Is player you are getting external or local?

**Comment by Tynopia** [comment]
The Player is local... Should i try it when the player is external?

**Comment by ham1255** [comment]
Whats your server version?

**Comment by Tynopia** [comment]
The newest of MultiPaper (1.19.2)

**Comment by ham1255** [comment]
Since 760 is 1.19.2 protocol,

I want to know few things like

Do you use viaversion somehow
And how like is it installed on the proxy(velocity or bungeecord) or minecraft server.

**Comment by Tynopia** [comment]
Yes i use viaversion... Does this hide the real version?

**Comment by ham1255** [comment]
Does it run on proxy? Or multipaper?

**Comment by Tynopia** [comment]
It runs only on MultiPaper Server

**Comment by ham1255** [comment]
Hmmm could you test that method on paper?  If it does you could report it at paper or viaversion not sure

**Comment by Tynopia** [comment]
![image](https://user-images.githubusercontent.com/65678882/215346087-5e995051-2dda-40f5-be40-b9df37261fd9.png)
![image](https://user-images.githubusercontent.com/65678882/215346094-f0af124f-b571-45c1-834f-2e6bb5facf70.png)

`Via.getAPI().getPlayerVersion(citybuildPlayer.uuid)`

I tried to check the protocol version over the ViaVersion API and it works... I think we can close that here 😄
