### ISSUE TITLE
Citizen

### ISSUE THREAD

**Issue by Tynopia** [MultiPaper/MultiPaper#325]
![image](https://user-images.githubusercontent.com/65678882/215455187-950fce93-0f44-48ea-a476-70e5a62abd12.png)

I wanted to create an NPC but no matter which 1.19.2 version of Citizen I use, I keep getting this error. I asked on the Citizen Discord and they suggested I reach out to you. Is this a known issue or do you perhaps already have a fix for it?

**Comment by DoctaEnkoda** [comment]
Use this version (beta) https://github.com/MultiPaper/MultiPaper/pull/319

**Comment by Tynopia** [comment]
Do I need to build the jar from this branch? https://github.com/DoctaEnkoda/MultiPaper/tree/fix-citizens

**Comment by DoctaEnkoda** [comment]
He ils build in Actions

**Comment by DoctaEnkoda** [comment]
https://github.com/MultiPaper/MultiPaper/actions/runs/3978995368

**Comment by Tynopia** [comment]
On 1.19.3 MultiPaper the error still exist... Is it possible to merge the changes from 1.19.2 to 1.19.3 MultiPaper?

**Comment by ham1255** [comment]
#355 was merged for 1.19.3 closing this.
