### ISSUE TITLE
mistake with ender eyes

### ISSUE THREAD

**Issue by Belceebuh** [MultiPaper/MultiPaper#330]
Hi, I am using MultiPaper 1.19.2 and for some strange reason when a person goes to the end portal and clicks on the portal frame, the eye is placed but it is thrown, it is as if it is duplicated, this causes the server to crash.

Log: https://mclo.gs/8zC3aYo

**Comment by ham1255** [comment]
Can you show video of this happening?

**Comment by ham1255** [comment]
Since crash report doesn't say much.

**Comment by Belceebuh** [comment]
Sure.

https://www.youtube.com/watch?v=S0ZIgXA-45o

**Comment by Belceebuh** [comment]
this time it didn't crash, I don't know why but it only happens sometimes.

**Comment by ham1255** [comment]
This looks similar to enderpearl   problem, where it desyncs if player on external chunks, are you by chance on external chunks

Run /mpdebug?

**Comment by Belceebuh** [comment]
https://www.youtube.com/watch?v=XGDyzIrZQEE

PS: sorry for the fps of the video, for some reason it was saved like this.

**Comment by ham1255** [comment]
hmmm then its not related, i will check it.

**Comment by Belceebuh** [comment]
okay, thanks.

**Comment by ham1255** [comment]
@Belceebuh Have you tested with no plugins? i have been trying to replicate this on nothing so far.

**Comment by Belceebuh** [comment]
@ham1255 Could it be because I use a custom world generator?

**Comment by ham1255** [comment]
Custom world generation does not mess with ender pearls

**Comment by ham1255** [comment]
can i see your list of plugins? 
run `/plugins` in your console and paste text output no screenshots please.

**Comment by Belceebuh** [comment]
Sure.

`Plugins (60): AlonsoTags, AureliumSkills, BetterRTP, ChatSentry, Chunky, Citizens, CMILib, CommandPanels, CustomHeads*, DeathMessages, DecentHolograms, DeluxeCoinflip, DeluxeCombat, DeluxeCombat_Addon_WG*, DeluxeMenus, eco, EcoEnchants, Essentials, EssentialsSpawn, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), Graves, GSit, InteractiveChat, Iris, ItemEdit, ItemsAdder, ItemTag, Jobs, LightAPI, LoneLibs, LPC, LuckPerms, MarriageMaster, MobFarmManager, Multiverse-Core, NBTAPI, NexEngine, PlaceholderAPI, PlayerKits, ProtocolLib, ShopGUIPlus, SkinsRestorer, sleep-most, spark, SternalBoard, TAB, TradePlus, UltimateClans, UltraCosmetics, Vault, ViaBackwards, ViaVersion, VoidGen, VotingPlugin, VoxelSniper, Vulcan, WorldBorder, WorldGuard, zAuctionHouseV3`

**Comment by ham1255** [comment]
Based on discord messages 
https://discord.com/channels/937309618743427113/937309618743427116/1071688069587144705
Its was Iris issues 


Closing as plugin issue.
