### ISSUE TITLE
Get all Online Players

### ISSUE THREAD

**Issue by Tynopia** [MultiPaper/MultiPaper#331]
![image](https://user-images.githubusercontent.com/65678882/216769028-1e91c18b-da44-4138-90f5-5eb5923fca36.png)

We have 2+ Players on the Multipaper Server but only one (The Local Player on this Server) is shown in Bukkit.getOnlinePlayers

![image](https://user-images.githubusercontent.com/65678882/216769070-e25c587f-3baf-4a8c-9d16-cb03e3b6c7a6.png)

**Our hotfix was to loop all local and external players and add it to a list (Thats not good but its the only way to get all players)**
![image](https://user-images.githubusercontent.com/65678882/216769149-d26266ae-d2e8-4d44-a81a-91c95198e0b8.png)

We use the newest Version of https://multipaper.io/download.html

**Comment by DoctaEnkoda** [comment]
Use MultiLib

**Comment by Tynopia** [comment]
getOnlinePlayers and getAllOnlinePlayers differented... Thanks <3

**Comment by ham1255** [comment]
i am reopening this issue as documentation issue since readme file does not mention existence of `bukkit#getAllOnlinePlayers()`

**Comment by PureGero** [comment]
Fixed in #331 on the 1.20.1 dev branch
