### ISSUE TITLE
Authme Bug

### ISSUE THREAD

**Issue by Shizuri23** [MultiPaper/MultiPaper#332]
https://user-images.githubusercontent.com/46082179/216780650-04ed8286-361a-40ab-9b4a-d556bced341a.mp4

**Comment by Shizuri23** [comment]
Delete Authme to return to normal

**Comment by DoctaEnkoda** [comment]
Online server = true

**Comment by Shizuri23** [comment]
> Online server = true

Is there any other way? Most of my friends are non-online

**Comment by xymb-endcrystalme** [comment]
We can't speak Chinese, we don't know what the error message is saying.

Put Authme on Paper or Velocity and forward players to MultiPaper after they are authenticated. It's best not to expose MultiPaper to the internet directly.

**Comment by DoctaEnkoda** [comment]
Piracy is piracy, go online and no bug

**Comment by Shizuri23** [comment]
> We can't speak Chinese, we don't know what the error message is saying.
> 
> Put Authme on Paper or Velocity and forward players to MultiPaper after they are authenticated. It's best not to expose MultiPaper to the internet directly.

Sorry, now I use back to English

**Comment by Shizuri23** [comment]
https://user-images.githubusercontent.com/46082179/216781037-352f99a0-e4a7-466d-a4cc-57acd1d47baa.mp4
