### ISSUE TITLE
CMI Alias command very strange

### ISSUE THREAD

**Issue by Shizuri23** [MultiPaper/MultiPaper#334]
When two or more Multipapers are running, the TAB completion function of CMI Alias fails

Current: git-MultiPaper-"f5e5dac" (MC: 1.19.3)*
Error obtaining version information
Previous version: git-MultiPaper-"8096d37" (MC: 1.19.3)

<img width="650" alt="image" src="https://user-images.githubusercontent.com/46082179/216808279-14122128-aed7-45c2-ba72-6f268787699c.png">

**Comment by Shizuri23** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/46082179/216808327-9d21da34-d275-4968-9418-2f509bc2b9bb.png">

<img width="587" alt="image" src="https://user-images.githubusercontent.com/46082179/216808313-2ba79390-8827-4ea6-9284-9e7deb968907.png">

**Comment by ham1255** [comment]
are sure your all servers have same plugins?

**Comment by Shizuri23** [comment]
I try to use https://github.com/MultiPaper/LuckPerms

problem solved now
