### ISSUE TITLE
The Forge client cannot access the server

### ISSUE THREAD

**Issue by Shizuri23** [MultiPaper/MultiPaper#337]
![{B1AAA684-0DC1-250A-8C71-725D8EF4846A}](https://user-images.githubusercontent.com/46082179/216955058-36de2e42-a66f-4f9a-8d91-ba2b964379a4.png)

Use Fabric to access the server normally

Current: git-MultiPaper-"843e95f" (MC: 1.19.3)*
Error obtaining version information
Previous version: git-MultiPaper-"f5e5dac" (MC: 1.19.3)

**Comment by ham1255** [comment]
how do you connect to your servers, seems like misconfiguration between servers and proxy(bungeecord or velocity)

**Comment by Shizuri23** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/46082179/216961489-6e539d92-e09b-4f93-9f16-a31e8609c919.png">

**Comment by Shizuri23** [comment]
> how do you connect to your servers, seems like misconfiguration between servers and proxy(bungeecord or velocity)

`# This is the main configuration file for MultiPaper.
# There's quite alot to configure. Read the docs for more information.
# 
# Docs: https://github.com/PureGero/MultiPaper/blob/main/MULTIPAPER_YAML.md 

master-connection:
  advertise-to-built-in-proxy: true
  master-address: localhost:35353
  my-name: server-2
optimizations:
  dont-save-just-for-lighting-updates: false
  reduce-player-position-updates-in-unloaded-chunks: false
  ticks-per-inactive-entity-tracking: 1
  use-event-based-io: true
peer-connection:
  compression-threshold: 0
  consolidation-delay: 0
sync-settings:
  files:
    files-to-not-sync:
    - plugins/bStats
    files-to-only-upload-on-server-stop:
    - plugins/MyPluginDirectory/my_big_database.db
    files-to-sync-in-real-time:
    - plugins/MyPluginDirectory/userdata
    files-to-sync-on-startup:
    - myconfigfile.yml
    - plugins/MyPlugin.jar
    log-file-syncs: true
  sync-entity-ids: true
  sync-json-files: true
  sync-permissions: true
  sync-scoreboards: true
  use-local-player-count-for-server-is-full-kick: false
`

**Comment by Shizuri23** [comment]
> how do you connect to your servers, seems like misconfiguration between servers and proxy(bungeecord or velocity)

Vanilla and Fabric can enter the server

**Comment by ham1255** [comment]
What mods are you running on forge?

**Comment by Shizuri23** [comment]
> What mods are you running on forge?

No mod

**Comment by ham1255** [comment]
Like i said above it seems like misconfiguration, but i will do some tests later.
