### ISSUE TITLE
Source Code Question

### ISSUE THREAD

**Issue by kindaepic** [MultiPaper/MultiPaper#341]
This might be a dumb question, but where can I find MultiPaperInventoryHandler and ExternalPlayer in the source code?

**Comment by ham1255** [comment]
apply server patches, and got to MultiPaper-Server
And search for package puregero.multipaper

**Comment by kindaepic** [comment]
After doing that and opening the source code in IntelliJ Community, I get these 2 errors:
Could not resolve all dependencies for configuration ':MultiPaper-Server:compileClasspath'.
Could not create task ':MultiPaper-Server:jar'.

**Comment by ham1255** [comment]
`./gradlew applyPatches` then for paper clip jar run `./gradlew createReobfPaperClipJar`

**Comment by kindaepic** [comment]
I've already did `./gradlew applyPatches`, I tried doing `./gradlew createReobfPaperClipJar` but I get this error: (I already have the code from applyPatches)
* What went wrong:
A problem occurred configuring project ':MultiPaper-Server'.
> Could not create task ':MultiPaper-Server:shadowJar'.
   > Could not create task ':MultiPaper-Server:jar'.
      > Command finished with 128 exit code: git -c commit.gpgsign=false -c core.safecrlf=false rev-parse --short=7 HEAD

**Comment by kindaepic** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/70847832/217383020-b9f7179d-0bba-45e7-b055-db4cc325314d.png)

**Comment by ham1255** [comment]
i think error means you don't have git setup read https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md

**Comment by kindaepic** [comment]
I did
`git init`
`git add .`
`git commit -am "Commit"`
and it got fixed. Thanks
