### ISSUE TITLE
getTrackedPlayers() does not work across different shards

### ISSUE THREAD

**Issue by amuazm** [MultiPaper/MultiPaper#348]
https://jd.papermc.io/paper/1.19/org/bukkit/entity/Entity.html#getTrackedPlayers()

<Entity>.getTrackedPlayers() is supposed to get all Players which are within render distance of the entity.
It does not work accross different shards.
After looking at the documentation, there seems to be no alternative for this method.

**Comment by ham1255** [comment]
Seems like intentional, waiting for @PureGero  response on discord.

**Comment by ham1255** [comment]
yup intentional adding documentation tag
