### ISSUE TITLE
MultiPaper error with Citizens

### ISSUE THREAD

**Issue by Belceebuh** [MultiPaper/MultiPaper#354]
Hello, I have the following problem with Citizens:

https://mclo.gs/4CtkbEr

I spoke to Citizens support and they told me that it is most likely a MultiPaper error plus they did not help me by finding the error.

**Comment by ham1255** [comment]
this actually a bug within the stats manager in the server that uploads the stats back to the master

**Comment by Belceebuh** [comment]
How can I solve it?

**Comment by ham1255** [comment]
there is active Pull Request to fix it but it was not updated to 1.19.3

**Comment by Belceebuh** [comment]
So all we can do is wait?

**Comment by ham1255** [comment]
i might Pr my own solution later this day.

**Comment by Belceebuh** [comment]
that would be great

**Comment by ham1255** [comment]
Duplicate of #325
