### ISSUE TITLE
Chunk corrupted

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#370]
I don't have any plugins installed, everything is running the server by default, but the blocks are corrupted like in the video, can anyone tell me what might be causing this?
https://youtu.be/yGXRhvz49RM
Server version: `git-MultiPaper-"bc53f8e" (MC: 1.19.3)*`
And after testing, the same problem also occurs in the latest dev version (`git-MultiPaper-"5ae3190" (MC: 1.19.4)*`).

**Comment by PureGero** [comment]
I'm gonna assume that this is also fixed by 490ec31 on the 1.20.1 dev branch, let me know if it isn't :)

**Comment by YTiceice** [comment]
Yes, the problem did not reappear in the test just now, thank you for your fix!
