### ISSUE TITLE
server stuck on pinging

### ISSUE THREAD

**Issue by Craftingnerf** [MultiPaper/MultiPaper#371]
I'm having an issue with several ubuntu servers running multipaper, whenever my friend connects his shards the server gets stuck on pinging, it could be a loopback issue, however whenever it was just my network we could connect just fine.

`multipaper build number #37`

how the network is currently:
```
mynetwork----internet-------friends network
multipaper master                 shard3
shard1                            shard4
shard2                            shard5
```
EDIT 2 : here is the error in the MultipaperMaster instance
![image](https://github.com/MultiPaper/MultiPaper/assets/69762814/f8ecc189-9f75-4aca-9de6-fa36d6f9bb0a)

EDIT : I've shut down my servers and it appears to be something with the master server and the shards over the internet not wanting to work
EDIT 3 : I've removed the world folders and the plugin folders (I realized it was redundant) and now I only get No available servers for <my local IP> to connect to (not a problem since my shards are down at the moment)
Edit 4 : once my friend started his servers back up the pinging issue started again
Edit 5 : my friend port forwarded one of his shards and still nothing
Edit 6 : I have since shut down the master server and I am no longer attempting to set this up
however I think it could be because I wasnt using a config for the proxy and I didnt list the ips and ports for the shards over the internet, however I also wasnt listing the local shards so I dont know what went wrong.

**Comment by PureGero** [comment]
Upload all your shard's multipaper.yml's and master command line arguments if you still want this to be resolved. You can find my discord on the discord server if you wish to private message them to me instead of uploading them here.
