### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [MultiPaper/MultiPaper#373]
just wondering if there was any chance that it would be updated to 1.20.x, or if there was a working fork/build that already is updated?

**Comment by KaspianDev** [comment]
Clone the repo, checkout to dev/1.20.1 branch and follow [these](https://github.com/MultiPaper/MultiPaper/tree/dev/1.20.1#building) steps.

**Comment by UltraHispeed-Elite** [comment]
Thanks for the information
