### ISSUE TITLE
This project is steil alive?

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MultiPaper/MultiPaper#377]
It's been a very long time since the last commit, what happened?

**Comment by hkfvbk** [comment]
The last commit was yesterday

**Comment by Mr-Ao-Dragon** [comment]
> The last commit was yesterday

Sorry, I didn't notice the dev branch, I'm glad the project is still alive, but the state of the project between April and June is really very worrying!

**Comment by KK964** [comment]
The MultiPaper project is provided for free by PureGero, and other opensource contributors. Unfortunately, not as much time can be spent on this project as we all would like; however, the need to up-keep livelihood is a much higher priority than a [passion project](https://justforfunnoreally.dev/). If you wish to help support the project, and to enable more frequent updates, consider [supporting PureGero](https://ko-fi.com/puregero).
