### ISSUE TITLE
Repeatedly generate ender dragon

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#379]
When there are multiple MultiPaper nodes, the Ender Dragon will spawn multiple times, in each MultiPaper console:
```
Scanning for legacy world dragon fight...
Found that the dragon has not yet been killed in this world.
```
And the corresponding number of boss bars will also be displayed on the player.
![image](https://github.com/MultiPaper/MultiPaper/assets/87787929/054d05f4-58cf-4cd4-acc0-87eddb846df7)
However, other dragons will not be displayed after the player defeats them, but will only be displayed after entering other portals.

MultiPaper version: https://github.com/MultiPaper/MultiPaper/commit/424e3711cd42691d3e627e354f6ad4e928a7f5c0
No plugins are installed except the default spark.

**Comment by PureGero** [comment]
Fixed with 66ae6a8
