### ISSUE TITLE
Bolt Plugin Fork

### ISSUE THREAD

**Issue by DebuffSensei** [MultiPaper/MultiPaper#384]
### Is your feature request related to a problem?

Hello Dear Devs,
I would really apreciate it if you could programm a fork for the Bolt Plugin that runs for MultiPaper Servers.
Bolt is one of the newest and best plugins to create locked Chests, Anvils, Blocks, Entities etc. and I am currently using it on my server.
However it hast some issues with MultiPaper as some securities may not work on different shards.
As it ist opensource I hope that my request gets a satisfying answer from you.
Best Wishes,
Debuff

### Describe the solution you'd like.

I want a fork for the opensource Bolt Plugin that works with MultiPaper and syncs all securites on the different nodes.
Connectivity with MySQL would also be appreciated and nessesary.

### Describe alternatives you've considered.

We tried lwc but it works even less and doesnt cover all features I want for my server.

### Other

https://www.spigotmc.org/resources/bolt.109679/?__cf_chl_rt_tk=tb0Pbg7K3Va.AefVMK6hS1VLIcy6gdqiXl5gFRLL6rQ-1698863516-0-gaNycGzND_s

This is the link to the Bolt Plugin

**Comment by PureGero** [comment]
I wouldn't get your hopes up, but I'll leave this issue open incase someone happens to see it.
