### ISSUE TITLE
Folia version?

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [MultiPaper/MultiPaper#389]
### Is your feature request related to a problem?

no, just curious

### Describe the solution you'd like.

will you be brining folia into the multipaper stuff to allow the individual server nodes to multithread.

### Describe alternatives you've considered.

no alternatives

**Comment by eugeniodevv** [comment]
what

**Comment by PureGero** [comment]
Folia's patches aren't planned on being imported into MultiPaper, as if you want multithreading on one machine, you can simply run multiple MultiPaper servers. Introducing Folia would add much more complexity that isn't seen as being worth it
